global using Basket.API.Models;
global using BuildingBlocks.CQRS;
global using Carter;
global using Mapster;
global using MediatR;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Behaviors;
global using Marten;
global using Basket.API.Exceptions;
